export BCOIN_NETWORK=regtest
export BCOIN_HTTP_HOST=0.0.0.0
export BCOIN_WALLET_HTTP_HOST=0.0.0.0
export BCOIN_NODE_HOST=0.0.0.0
export BCOIN_LOG_LEVEL=debug
export BCOIN_WORKERS=true
export BCOIN_LISTEN=true
export BCOIN_MEMORY=false
export BCOIN_INDEX_TX=true
export BCOIN_INDEX_ADDRESS=true
export BCOIN_INDEX_FILTER=true
export BCOIN_API_KEY=apiapiapiapikey!
export BCOIN_WALLET_API_KEY=apiapiapiapikey!
export BCOIN_PREFIX=$PWD/_bcoin
export BCOIN_BIP157=true
alias BCOIND="$PWD/node_modules/bcoin/bin/bcoin --daemon"
alias BL="tail -F $PWD/_bcoin/regtest/debug.log"
alias KB="killall bcoin; killall bitcoind"
alias RR="rm -rf $PWD/_bcoin; rm -rf $PWD/_bitcoind; mkdir $PWD/_bitcoind"
alias BITCOIND="bitcoind -regtest -blockfilterindex -datadir=$PWD/_bitcoind -rpcpassword=x -daemon"
alias CONNECT="bcoin-cli rpc addnode 127.0.0.1:18444 add"
